default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: coeus_development

test:
  <<: *default
  database: coeus_test

production:
  <<: *default
  database: coeus_production
